services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "7333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always  # Ensures restart on system reboot

volumes:
  qdrant_data:
    driver: local
